### ISSUE TITLE
Redo auto align for cones

### ISSUE THREAD

**Issue by owenflatman** [Frc5572/FRC2023#133]

**Comment by owenflatman** [comment]
Auto alignment for cones depends on cone being in the middle.

**Comment by legoguy1000** [comment]
Thoughts on how to account for non centered cone?

**Comment by owenflatman** [comment]
Change the alignment so the cone is not dependent on being centered, and has a faster and more accurate way to line up so manual

**Comment by legoguy1000** [comment]
Curious on ur thoughts on how to do that? How do u know how to adjust?

**Comment by legoguy1000** [comment]
Maybe we can use the ultrasonic distance sensor to try to determine how far from center a cone is? I don't even know how accurate that will be and I don't really have any ideas on how to know how to adjust for an off center cone.

**Comment by legoguy1000** [comment]
This seemed to work very well for auto, IDK about tele.
