### ISSUE TITLE
180 rotation after leaving community auto

### ISSUE THREAD

**Issue by aidan-underwood** [Frc5572/FRC2023#137]

**Comment by legoguy1000** [comment]
Can u add more details? Currently the robot will be facing the driver station wall if leaving community and not climbing? Are we wanting it to turn around and face away?

**Comment by aidan-underwood** [comment]
> Can u add more details? Currently the robot will be facing the driver station wall if leaving community and not climbing? Are we wanting it to turn around and face away?

During auto, if we run it and decide to not dock, the robot finishes facing the driver station wall. To increase efficiency, let's rotate after we finish the path so we can face the opponent driver station wall.
