### ISSUE TITLE
Create Auto-Balancing Command

### ISSUE THREAD

**Issue by agrinmanriv0537** [Frc5572/FRC2023#18]
Could be using gyro or just april tags.
[Example](https://fb.watch/i4pOZBqCTx/)

**Comment by agrinmanriv0537** [comment]
https://fb.watch/i4pOZBqCTx/

**Comment by legoguy1000** [comment]
looks like these guys were able to use a basic PID method to work 
https://www.chiefdelphi.com/t/warning-to-everyone-working-on-auto-balance/422460/27?u=legoguy1000
https://github.com/GOFIRST-Robotics/Ri3D-2023/blob/main/src/main/java/frc/robot/commands/BalanceOnBeamCommand.java
