### ISSUE TITLE
Swerve Subsystem

### ISSUE THREAD

**Issue by owenflatman** [Frc5572/FRC2023#5]
This subsystem will need to include:

- 4 canCoders
- NavX Gyro

Possible but likely functions include:

- Drive
- WheelsIn (Position all the wheels to face into the robot)
- setMotorsZero (Sets all motors to zero or inactive)
- setModuleState (For Autonomous)
- getPose (Returns position on field)
- resetOdometry (Reset robot position on field)
- zeroGyro (Resets gyro to zero offset)
- getYaw (Get rotation degree from swerve modules)
- getRotation
- useOutput (For Autonomous)

**Comment by agrinmanriv0537** [comment]
Change SwerveDriveOdometry to SwerveDrivePoseEstimator. Also send robot odometry to dashboard to be seen on the field.
