### ISSUE TITLE
Fix auto dock command

### ISSUE THREAD

**Issue by owenflatman** [Frc5572/FRC2023#92]
Tried running command today, robot moved in opposite direction every time, despite gyro or robot position.

**Comment by wilsonwatson** [comment]
What does "opposite direction" mean?

**Comment by legoguy1000** [comment]
Same question? It's hard coded to move backwards.

**Comment by legoguy1000** [comment]
I pushed stone additional logic to #89 to enhance the climbing command. It will now dock the arm if not already and then rotate so ur always facing away from the platform based on ur position on the field. The x value probably needs to be adjusted though.

**Comment by owenflatman** [comment]
We would like the back of the robot up for it to climb, but it move move forwards rather than backwards. I tried resetting the gyro, but it still went forward. Alex also couldn't get it to work

**Comment by legoguy1000** [comment]
So it depends on the odometry, reseting the gyro only affects teleop driving, not any of the automation
